name: google_maps_flutter_web_sample
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.4.5
  firebase_core: ^2.8.0
  flutter:
    sdk: flutter
  geoflutterfire_plus: ^0.0.6
  google_maps_flutter: ^2.2.5
  google_maps_flutter_web: ^0.4.0+7
  rxdart: ^0.27.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
